fleetz/urls.py
from django.contrib import admin
from django.urls import path, include

import fleetz.views as views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('profile/', views.ProfileView.as_view(), name='user_profile'),
    path('schedule/', views.ScheduleView.as_view(), name='schedule_tweet'),
    path('disconnect/<int:user_id>/', views.DisconnectView.as_view(), name="disconnect"),
    path('unschedule/<str:tweet_id>/', views.UnscheduleTweetView.as_view(), name="unschedule"),
]

fleetz/models.py
from datetime import datetime, timedelta
import logging
import os
import re

from allauth.account.signals import user_signed_up
from allauth.socialaccount.models import SocialApp, SocialAccount, SocialToken
from background_task import background
from background_task.models import Task
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.dispatch import receiver
from django.utils.timezone import make_aware
import tweepy

from fleetz.core import AUTH, QUOTED_TWEET_REGEX


logger = logging.getLogger('fleetz')


class FleetzUser(models.Model):
    """ This model houses and handles a users Fleetz info.

    triggers: comma separated list of values to be used to delete tweets
    hours, minutes: time in hours or minutes to wait before deleting the tweet, based on the time it was posted
    tweets: comma separated list of tweets to be deleted.

    """
    user = models.OneToOneField(User, related_name='user_account', null=False, 
                                blank=False, on_delete=models.CASCADE, editable=False)
    hours = models.IntegerField(default=24, null=False, blank=False)
    minutes = models.IntegerField(default=24, null=False, blank=False)
    triggers = ArrayField(models.CharField(max_length=1, default="*"), size=5, default=['*','*'])

    @property
    def social_account(self):
        return SocialAccount.objects.get(user=self.user)

    @property
    def social_token(self):
        return SocialToken.objects.get(account=self.social_account)

    @property
    def api_object(self):
        # Configure user auth credentials
        ACCESS_TOKEN = self.social_token.token
        ACCESS_TOKEN_SECRET = self.social_token.token_secret
        AUTH.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
        return tweepy.API(AUTH)

    @property
    def fetch_scheduled_tweets(self):
        """ This method returns the list of tweet objects scheduled for deletion
        from Twitter using Tweepy.
        """
        tweet_ids = [int(t.verbose_name) for t in Task.objects.filter(creator_object_id=self.user.id)]

        if tweet_ids:
            tweets_objs = self.api_object.statuses_lookup(tweet_ids)
            tweets = [t._json for t in tweets_objs]

            for t in tweets:
                created_at = datetime.strptime(t['created_at'], "%a %b %d %H:%M:%S %z %Y")
                task = Task.objects.filter(verbose_name=t['id']).first()
                t['created_at'] = created_at.isoformat()
                t['deleted_at'] = task.run_at.isoformat()

            return tweets

    def fetch_and_schedule_tweets(self):
        """ This function fetches a user's recent tweets and schedules their deletion

        Parameters
        ----------
        user_id : int, required
            the id of the Django user object

        TODO: is 25 tweets in the last hour enough or overkill?
        """
        def _filter_tweets(tweet):
            """ Use Regex to extract text from quoted replies, then proceed with the filtering
            """
            if str(tweet.id) not in scheduled_tweets and tweet.created_at >= since and tweet.text[:2] != 'RT':
                tweet.text = re.sub(QUOTED_TWEET_REGEX, '', tweet.text)
                return tweet

        scheduled_tweets = [t.verbose_name for t in Task.objects.filter(creator_object_id=self.user.id)]
        count = 0

        logger.info(f"Fetching tweets for user_id: {self.social_account.extra_data['screen_name']}")

        tweets = tweepy.Cursor(self.api_object.user_timeline).items(25)
        since = datetime.now() - timedelta(hours=settings.CRON_JOBS_INTERVALS_IN_HOURS)
        filtered_tweets = filter(_filter_tweets, tweets)

        for tweet in filtered_tweets:
            if any(trigger == tweet.text[-1] for trigger in self.triggers):
                # schedule tweets for deletion
                deletion_time = tweet.created_at + timedelta(hours=self.hours, minutes=self.minutes)
                delete_tweet(self.user.id, tweet.id, schedule=make_aware(deletion_time), creator=self.user, verbose_name=tweet.id)
                count += 1

        logger.info(f"Scheduled {count} of {self.social_account.extra_data['screen_name']}'s tweets for deletion'")


@background
def delete_tweet(user_id, tweet_id):
    """ This function deletes a single tweet. It runs as a background task.

    Parameters
    ----------
    user_id : int, required
        the user id of the tweet owner
    tweet_id : int, required
        the id of the tweet to be deleted
    """
    fleetz_user = FleetzUser.objects.get(user_id=user_id)
    fleetz_user.api_object.destroy_status(tweet_id)


@receiver(user_signed_up)
def handle_user_signed_up(sender, **kwargs):
    """ Create a new FleetzUser model for each user when they sign up.
    """
    if user := kwargs['user']:
        FleetzUser.objects.create(user=user)

fleetz/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.postgres.forms import SimpleArrayField

from .models import FleetzUser


class ProfileForm(forms.ModelForm):
    triggers = SimpleArrayField(forms.CharField(), delimiter='|')

    class Meta:
        model = FleetzUser
        fields = ('hours', 'minutes')

fleetz/views.py
from datetime import datetime, timedelta
import re

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.timezone import make_aware
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import FormView

from allauth.socialaccount.models import SocialAccount, SocialToken
from background_task.models import Task
from tweepy.error import TweepError

from fleetz.forms import ProfileForm
from fleetz.models import FleetzUser, delete_tweet
from fleetz.core import TWEET_URL_REGEX


class ProfileView(LoginRequiredMixin, FormView):
    """ This view allows a user to manage their profile, triggers and
    disconnect their Twitter account.
    """
    template_name = "fleetz/profile.html"
    form_class = ProfileForm
    success_url = "/profile/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_fleetz_details = FleetzUser.objects.get(user=self.request.user)
        user_social_account = user_fleetz_details.social_account
        user_social_token = user_fleetz_details.social_token
        context['form'] = ProfileForm(instance=user_fleetz_details)
        context['tweets'] = user_fleetz_details.fetch_scheduled_tweets

        context['user_extra_data'] = {
            'twitter_username': user_social_account.extra_data['screen_name'],
            'twitter_name': user_social_account.extra_data['name'],
            'bio': user_social_account.extra_data['description'],
            'profile_picture_url': user_social_account.extra_data['profile_image_url_https'],
            'profile_background_image_url': user_social_account.extra_data['profile_background_image_url_https'],
            'user_token': user_social_token.token,
            'user_token_secret': user_social_token.token_secret,
            'triggers': '|'.join(user_fleetz_details.triggers),
            'hours': user_fleetz_details.hours,
            'minutes': user_fleetz_details.minutes,
        }

        return context

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        fleetz_obj = FleetzUser.objects.get(user=self.request.user)
        if cleaned_data.get('hours') is not None:
            fleetz_obj.hours = form.cleaned_data['hours']
        if cleaned_data.get('minutes') is not None:
            fleetz_obj.minutes = form.cleaned_data['minutes']
        if cleaned_data.get('triggers'):
            fleetz_obj.triggers = form.cleaned_data['triggers']

        fleetz_obj.save()
        # messages: https://docs.djangoproject.com/en/2.2/ref/contrib/messages/#using-messages-in-views-and-templates
        messages.success(self.request, 'Details updated successfully.')

        return super().form_valid(form)


class ProfileFormView(LoginRequiredMixin, FormView):
    form_class = ProfileForm
    template_name = "fleetz/profile_form.html"
    success_url = "/profile/"


class DisconnectView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if user_id := kwargs['user_id']:
            User.objects.get(id=user_id).delete()
            return HttpResponseRedirect('https://twitter.com/settings/applications/17228896')

        messages.error(self.request, 'Something went wrong. Try again.', extra_tags='danger')
        return HttpResponseRedirect(reverse('user_profile'))


class ScheduleView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if request.POST.get('tweetUrl') and request.POST.get('twitterUsername'):

            if match := re.search(TWEET_URL_REGEX, request.POST['tweetUrl']):
                tweet_details = match.groupdict()

                if tweet_details['username'] == request.POST['twitterUsername']:
                    schedule_tweet(self.request, tweet_details['tweet_id'])

                elif tweet_details['username'] != request.POST['twitterUsername']:
                    messages.error(self.request, 'That is not your tweet.', extra_tags='danger')

            else:
                messages.error(self.request, 'Invalid tweet URL.', extra_tags='danger')
        else:
            messages.error(self.request, 'Something went wrong. Please try again.', extra_tags='danger')

        return HttpResponseRedirect(reverse('user_profile'))


class UnscheduleTweetView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if tweet_id := kwargs.get('tweet_id'):
            task = Task.objects.get(verbose_name=str(tweet_id))
            if task:
                task.delete()
                messages.success(self.request, 'Tweet removed from deletion schedule.')
            else:
                messages.error(self.request, 'Tweet not found.', extra_tags='danger')

        return HttpResponseRedirect(reverse('user_profile'))


class HomeView(TemplateView):
    """ This is the landing page of the application
    """
    template_name = "fleetz/home.html"


def schedule_tweet(request, tweet_id):
    """ This function takes in a single tweet id and schedules it's deletion.
    """
    try:
        tweet_task = Task.objects.get(verbose_name=tweet_id)
        messages.warning(request, 'Tweet is already scheduled for deletion.')

    except Task.DoesNotExist:
        fleetz_user = FleetzUser.objects.get(user=request.user)

        try:
            tweet = fleetz_user.api_object.get_status(tweet_id)

            deletion_time = tweet.created_at + timedelta(hours=fleetz_user.hours, minutes=fleetz_user.minutes)
            delete_tweet(request.user.id, tweet.id, schedule=make_aware(deletion_time), creator=request.user, verbose_name=tweet.id)

            messages.success(request, 'Tweet scheduled for deletion successfully.')

        except TweepError as e:
            msg = 'We ran into an error scheduling that tweet. Please check and try again'
            if e.response.status_code == 404:
                msg = 'Tweet not found. Please check and try again'

            messages.error(request, msg, extra_tags='danger')

fleetz/templates/fleetz/home.html
{% extends 'base.html' %}

{% load socialaccount %}
{% get_providers as socialaccount_providers %}

{% block content %}

<div class="jumbotron jumbotron-fluid mt-2 bg-transparent">
  <div class="container">
    <h1 class="display-4 text-center">Fleetz .:!:.</h1>
    <p class="lead text-center">
      Fleetz is a bot that lets you post self-destructing tweets.
    </p>
    <hr class="my-4">

    <div class="card-deck">
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">
            Fleetz allows you to configure how long a posted tweet stays up on Twitter. 
          </p>
          <p class="card-text">
            By default, the bot will delete any cadidate tweets after 24 hours and 24 minutes. A candidate tweet is a tweet having any of the specific triggers or characters as the last character of the tweet.
          </p>
        </div>
      </div>

      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">
            It periodically fetches your tweets in batches and checks for any trigger characters at the end of the tweet.
          </p>
          <p class="card-text">
            These triggers are the last character of a tweet and can be any character or emoji, apart from a pipe character(<strong>&nbsp;|&nbsp;</strong>).
          </p>
        </div>
      </div>
    
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">
            This duration before a tweet is deleted is configurable in the profile page.
          </p>
          <p class="card-text">
            On the same page, you also be able to see any tweets that are scheduled for deletion, when they will be deleted, and 
            you can unschedule a Tweet to avoid its deletion.
          </p>
        </div>
      </div>
    
    </div>

    <hr class="my-4">

    {% if user.is_authenticated %}

      <a class="btn btn-primary btn-md float-right" href="https://github.com/ro6ley/fleetz" role="button">Learn more</a>

    {% else %}

      {% if socialaccount_providers %}
        {% for provider in socialaccount_providers %}
          {% if provider.id == "twitter" %}
            <a title="{{provider.name}}" class="btn btn-primary btn-md float-right socialaccount_provider {{provider.id}}" href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">
              Log In with {{provider.name}} <i class="fas fa-sign-in-alt"></i>
            </a>
          {% endif %}
        {% endfor %}
      {% endif %}

  {% endif %}
  </div>
</div>

{% endblock %}

fleetz/templates/fleetz/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}

  <div class="row mt-2 mb-2">
    <div class="mx-auto col-lg-6">

      <div class="card">
        <div class="card-header">
          <h4 class="mb-0">Edit Your Profile</h4>
        </div>

        <div class="card-body">
          <form class="form" method="POST" action="{% url 'user_profile' %}" role="form" autocomplete="off">
            {% csrf_token %}
            <div class="row">
              <div class="col d-flex align-items-center justify-content-center">
                <div class="media">
                  <img src="{{ user_extra_data.profile_picture_url }}" class="img-thumbnail rounded-circle mr-3"/>
                  <div class="media-body">
                    <h5 class="mt-0">{{ user_extra_data.twitter_name }}</h5>
                    <span class="text-muted">@{{ user_extra_data.twitter_username }}</span>
                  </div>
                </div>
              </div>
            </div>

            <hr>

            <div class="form-group row">
              <label for="id_triggers" class="col-lg-3 col-form-label form-control-label">Triggers:</label>
              <div class="col-lg-9">
                <input class="form-control" type="text" name="triggers" value="{{ user_extra_data.triggers }}" maxlength="100" required id="id_triggers" aria-describedby="triggersHelpBlock">
                <small id="triggerHelpBlock" class="form-text text-muted">
                  Enter up to five(5) alphanumeric characters or symbols or emojis separated by pipe characters (<strong>&nbsp;|&nbsp;</strong>) to tag tweets for deletion, words will be ignored.
                  These triggers should be the last character of the tweets you want to tag for deletion after the elapsed time set above.
                  Default value is an asterisk(*).

                  <br><br>

                  For example, if you have the following triggers: <mark>*|😑|🤣</mark>; any tweet that ends in either
                  <mark>*</mark> or <mark>😑</mark> or <mark>🤣</mark> will be deleted after the duration set below.
                </small>
              </div>
            </div>

            <div class="row">
              <div class="col-lg3">

              </div>

            </div>

            <div class="form-group row">
              <label for="duration_row" class="col-lg-3 col-form-label form-control-label" aria-describedby="durationHelpBlock">Duration:</label>
              <div class="col-lg-9">

                <div class="form-row" id="duration_row">
                  <div class="form-group col-md-6">
                    <label for="id_hours"><small>Hours</small></label>
                    <input class="form-control" type="number" name="hours" value="{{ user_extra_data.hours }}" id="id_hours">
                  </div>
                  <div class="form-group col-md-6">
                    <label for="id_minutes"><small>Minutes</small></label>
                    <input class="form-control" type="number" name="minutes" value="{{ user_extra_data.minutes }}" id="id_minutes">
                  </div>
                </div>

                <small id="durationHelpBlock" class="form-text text-muted">
                  Enter the duration in hours after which the tweet will be deleted. This is relative to the time the tweet was posted.
                  By default the bot will delete a tagged tweet 24 hours and 24 minutes after it was posted.
                </small>
              </div>
            </div>

            <div class="form-group row">
              <label class="col-lg-3 col-form-label form-control-label"></label>
              <div class="col-lg-9 float-right">
                <a class="btn btn-secondary" href="{% url 'home' %}">Cancel</a>
                <input type="submit" class="btn btn-primary float-right" value="Save Changes">
              </div>
            </div>

          </form>

          <p class="text-center"><strong>You are all set now, you can get back tweeting.</strong></p>

          <hr/>

          <p>If you wish to disconnect this app from your Twitter account, 
            click the button below. This will delete you account on Fleetz then
            redirect you to Twitter where you can revoke Fleetz from accessing
            your account in the future.</p>
          <p>Click on <span class="text-danger">Revoke access</span> 
            in the page that opens to complete the process.</p>
          <p>You can always sign in with Twitter to rejoin Fleetz.</p>
          <a class="btn btn-danger float-right" href="{% url 'disconnect' user_id=user.id %}" data-confirm="Are you sure you want to delete your Fleetz account and disconnect it from your Twitter?">Disconnect</a>

        </div>
      </div>
      
    </div>

    <div class="mx-auto col-lg-6">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col">
              <h4 class="mb-0">Deletion Queue{% if tweets %}({{ tweets|length }}){% endif %}</h4>
            </div>
            <div class="col">
              <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#tweetUrlModal" data-placement="top" title="Manually add a tweet to the deletion schedule.">+</button>

              <!-- Tweet URL Modal -->
              <div class="modal fade" id="tweetUrlModal" tabindex="-1" role="dialog" aria-labelledby="tweetUrlModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="tweetUrlModalLabel">Manually schedule a tweet</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <form class="form" method="POST" action="{% url 'schedule_tweet' %}">
                      {% csrf_token %}
                      <div class="modal-body">
                        Enter the tweet URL below to manually schedule it for deletion.
                        <input type="hidden" id="twitterUsername" name="twitterUsername" value="{{ user_extra_data.twitter_username }}">
                        <div class="form-group">
                          <input type="text" class="form-control" id="tweetUrl" name="tweetUrl" placeholder="https://twitter.com/{{ user_extra_data.twitter_username }}/status/....">
                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Dismiss</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                      </div>
                    </form>
  
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="list-group list-group-flush">
            {% if tweets %}
              
              {% for tweet in tweets %}
                {% include 'fleetz/single_tweet.html' with tweet=tweet %}
              {% endfor %}

            {% else %}
              <p class="text-muted">You have no tweets scheduled for deletion at this time.</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

fleetz/templates/fleetz/single_tweet.html
<!-- Display s single tweet in the scheduled tweets section -->
<div class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
        <h6 class="mb-1">{{ tweet.user.name }} <span class="text-muted">@{{ tweet.user.screen_name }}</span></h6>
        <a href="https://twitter.com/{{ tweet.user.screen_name }}/status/{{ tweet.id_str }}" target="_blank"><small class="text-muted time">{{ tweet.created_at }}</small></a>
    </div>

    <p>{{ tweet.text }}</p>

    <small class="text-muted">To be deleted on: <span class="time">{{ tweet.deleted_at }}</span></small>  <a href="{% url 'unschedule' tweet_id=tweet.id %}" class="badge badge-danger float-right col-lg-3" data-confirm="Are you sure you want to unschedule this tweet from being deleted?">Unschedule</a>
</div>